// <auto-generated />
using CATALOGSERVICE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251108142409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CATALOGSERVICE.Modele.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 45m,
                            Quantity = 5,
                            Title = "How to get a good grade in DOS in 40 minutes a day",
                            Topic = "distributed systems"
                        },
                        new
                        {
                            Id = 2,
                            Price = 50m,
                            Quantity = 10,
                            Title = "RPCs for Noobs",
                            Topic = "distributed systems"
                        },
                        new
                        {
                            Id = 3,
                            Price = 40m,
                            Quantity = 3,
                            Title = "Xen and the Art of Surviving Undergraduate School",
                            Topic = "undergraduate school"
                        },
                        new
                        {
                            Id = 4,
                            Price = 30m,
                            Quantity = 7,
                            Title = "Cooking for the Impatient Undergrad",
                            Topic = "undergraduate school"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
